### ISSUE TITLE
Looks good!

### ISSUE THREAD

**Issue by Nokomis449** [pokiiio/node-red-contrib-web-page-screenshot#1]
This is just what I need, and I'm anxiously awaiting an ARM version since my Node-RED's run on Raspberry Pi's.

**Comment by pokiiio** [comment]
Let me find out for you.
Please wait for update...

**Comment by pokiiio** [comment]
https://github.com/pokiiio/node-red-contrib-web-page-screenshot/tree/v0.0.4

At the latest version, we can configure a path of Chromium as `executablePath` option. If headless Chromium is available on your Raspberry Pi, please set the path to `executablePath`. (`/usr/bin/chromium-browser`, generally)

I check this node working with the latest Raspbian OS(April 2019) and Raspberry Pi 3B.

**Comment by pokiiio** [comment]
Now updated node is also available on flow library. Please check this.
https://flows.nodered.org/node/node-red-contrib-web-page-screenshot
